# Generated by Django 4.1.3 on 2022-12-01 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('episodios', models.CharField(blank=True, max_length=255)),
                ('temporadas', models.CharField(blank=True, max_length=255)),
                ('lançamento', models.DateField()),
                ('sinopse', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%D')),
            ],
        ),
        migrations.CreateModel(
            name='Jogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('lançamento', models.DateField()),
                ('desenvolvedora', models.CharField(max_length=255)),
                ('descrição', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%D')),
            ],
        ),
        migrations.CreateModel(
            name='TipoHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
                ('lançamento', models.DateTimeField()),
                ('especificações', models.TextField(blank=True)),
                ('mostrar', models.BooleanField(default=True)),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%D')),
                ('peça', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.tipohardware')),
            ],
        ),
    ]
