# Generated by Django 4.1.3 on 2022-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animes',
            name='episodios',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='animes',
            name='temporadas',
            field=models.IntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='lançamento',
            field=models.DateField(),
        ),
    ]
